   var GAME_LEVELS = [

  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                   o            ",
   "                   o                                                            ",
   "                                                                  yyy           ",
   "                  yyy                              yy     yyy    yy!yy          ",
   "                                     o o     yyyy               y!!!!!y         ",
   "                                                                 yy!yy          ",
   "                                    yyyyy                         yvy           ",
   "            yy                                                              yy  ",
   "  yy           o                          o o                                y  ",
   "  y    yy               o                                                    y  ",
   "  y         yyyyyy               o        yyyyy                    o       o y  ",
   "  y         y                                                                y  ",
   "  y @       y          y                                         yyyyy       y  ",
   "  yyyy  yyyyyyy  yyyyyyyyyyyyyyy   yyyyyyyy  yyyyyyyyyy     yyyyyyyyyyyyyyyyyy  ",
   "     y!!y     y!!y             y   y                  y     y                   ",
   "     y!!y     yyyy             y!!!y                  y!!!!!y                   ",
   "     yyyy                      y!!!y                  y!!!!!y                   ",
   "                               yyyyy                  yyyyyyy                   ",
   "                                                                                ",
   "                                                                                "],


  ["                                                                                                                y ",
   "                                                                                                                y ",
   "                                                                                                                y ",
   "                                                                                                                y ",
   "   o                                                                                                          o y ",
   "           o                                                       yyyyy                                        y ",
   " yyyy                   o                                                                                       y ",
   "                                                                               yyyy                        yyyyyy ",
   "         yyyyy                                      oo                                                            ",
   "                           >                                                                                      ",
   "                                                                              >>>>>                               ",                                                                           
   "    ^            yyyyy                 y        o yyyyyy                                                          ",
   "                                       y          y                                       >>>>>                   ",
   "      >      o                         y       yyyy          >>>>>                 o                              ",
   "                                  ?    y          y                                                               ",
   "          yyyyy                        y o        y                                                ^^^^^          ",
   "                                       y          y                                                               ",
   " @                                     yyyy       y                        >>>>>                                  ",
   "yyyyy!!!yy                             y          y                                                               ",
   "    y!!!!y                             y        o y                                                               ",
   "    y!!!!y                             y          y                                                               ",
   "    yyyyyy                             y       yyyy                                                               ",
   "                                                  y                                                               ",
   "                               >                  y                                                               ",
   "                                                  y        xxx xxx xxxx          xxxxx  xx     xxxxxx x    xx  xx ",
   "yyyyyyyyyyyyyyy   yyyyy                           y      yyyyyyyyyyyyy           yyyyyyyyy     yyyyyyyy    yyyyyy ",
   "                      y                           y                                                               ",     
   "              o       y             ?             y                                                               ",   
   "                      y                           y                                                               ",
   "        o   yyyyyy    y      >                    y                                                               ",
   "                      y                           y                                                               ",
   "       yyyy           yxxxxxxxxxxxxxxxxx?xxxxxxxxxy                       ^^^^                                    ",
   "                      yyyyyyyyyyyyyyyyyyyyyyyyyyyyy                                                               ",
   "yyyyy                                                                                                             ",
   "             o                     o                      o              o                      o                 ",
   "                                                                  ?                 ?                             ",
   "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"],
   
   
   ["                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "  o                                                                                       o                                  ",
   "                                 >>>>>>>                                                                                     ",
   "yyyyy                                                                                                                        ",
   "                    yyyy                                                                                                     ",
   "                                                        yyyyyyyyy  yyy  yyyyy                                    yyyyyyyyyy  ",
   "                                                        y!!y            y!!!y                                       o o o y  ",
   "                                                        y!!!y         yy!!!!y                                    yyyyyyyyyy  ",
   "             >>>>>                                      y!!!!y       y!!!!!!y                >>>>>>>>                        ",
   "                                                        y!!!!!y     y!!!!!!!y                                                ",
   "                                o                       y!!!!!!y   y!!!!!!!!y                                                ",
   "                                                        y!!!!!!!yoy!!!!!!!!!y       ^^^^^^^                                  ",
   "                             y-yyyyyy                    y!!!!!!!yyy!!!!!!!!!y                         >>>>>                 ",
   "                                                        y!!!!!!!!!!!!!!!!!!!y                                                ",
   "                                          o             y!!!!!!!!!!!!!!!!!!!y                                                ",
   "                     o                                  y!!!!!!!!!!!!!!!!!!!y                                                ",
   "                   >>>>>>                               yyyyyyyyyyyyyyyyyyyyy                 yyyyyyy                        ",
   "  @                                                      yyyyyyyyyyyyyyyyyyy                                                 ",
   "yyyyy                                                     yyyyyyyyyyyyyyyyy                                                  ",
   "                                                           yyyyyyyyyyyyyyy                                                   ",
   "                                                           y                                                                 ",
   "         ^^^^    yyyyyyy               ^^^^^^              y                                             o                   ",
   "                                                           yo                                         ^^^^^^                 ",
   "                                                           y                                                                 ",
   "                                                           yxx                                                               ",
   "                                                           yyyyyyyyy                                                         ",
   "   o                                                       !!!!!!!!y                                                         ",
   "                                                           !!!!!!!!yyyyyyy                                                   ",
   "                                                           !!!!!!!!!!!!!!y                   yyyyy                           ",
   "yyyyyyyyyyyyy                                              !!!!!!!!!!!!!!y                                                   ",
   "                                                           !!!!!!!!!!!!!!y                                                   ",
   "                                                           !!!!!!!!!!!!!!y       yyyyyy                                      ",
   "                                                           yyyyyyyyyyyyyyy                                                   ",
   "                     >>>>>                                 y o o o o o o                         >>>>>                       ",
   "                                                           y                                                                 ",
   "                                                           yyyyyyyyyyyyyyyy         >                                        ",
   "                                                                                                                             ",
   "             ?          xxxx                      ?                                 xxxx              ?             xxxxxxxxx",
   "yyyyyyyyyyyyyyyyxxxyyyyyyyyyyyyyyy     yyyyyyyyyyyyyyyyyyyyyy      yyyyyyyyyyyyyyyyyyyyyyyy      yyyyyyyyyyyyyyyyyyyyyyyyyyyy",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   
 
  ["                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "         y       y   yyyyyyyyyyy    y          y                                                                             ",
   "          y     y    y         y    y          y                                                                             ",
   "           y   y     y         y    y          y                                                                             ",
   "            y y      y         y    y          y                                                                             ",
   "             y       y         y    y          y                                                                             ",
   "             y       y         y    y          y                                                                             ",
   "             y       y         y    y          y                                                                             ",
   "             y       y         y    y          y                                                                             ",
   "             y       y         y    y          y                                                                             ",
   "             y       yyyyyyyyyyy    yyyyyyyyyyyy                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                        y              y    yyyyyyyyyyyyyy     yyy           y        y                      ",
   "                                        y              y           y           y  y          y        y                      ",
   "                                        y              y           y           y   y         y        y                      ",
   "                                        y              y           y           y    y        y        y                      ",
   "                                        y              y           y           y     y       y        y                      ",
   "                                        y              y           y           y      y      y        y                      ",
   "                                        y              y           y           y       y     y        y                      ",
   "                                        y       y      y           y           y        y    y        y                      ",
   "                                        y       y      y           y           y         y   y        y                      ",
   "                                        y       y      y           y           y          y  y        y                      ",
   "                                        y       y      y           y           y           yyy                               ",
   "                                        yyyyyyyyyyyyyyyy    yyyyyyyyyyyyyy     y           yyy        y                      ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             "],
   
   
  
];

if (typeof module != "undefined" && module.eyports)
  module.eyports = GAME_LEVELS;
